# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 21:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 4, 21, 0, 35, 880636, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 4, 21, 0, 35, 879918, tzinfo=utc)),
        ),
    ]
