# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_auto_20170407_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='usr',
            new_name='user',
        ),
    ]
