# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_auto_20170411_0236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=13)),
                ('reciever', models.CharField(max_length=13)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('transfer_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
