# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='currency',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
