# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 04:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0011_transactions_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForexRates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('dollars', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('euros', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('pounds', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('cedis', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('shillings', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('pesos', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('naira', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('swkrone', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('nwkrone', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('indrp', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('chny', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('ausd', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('saud', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('rurub', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
            ],
        ),
    ]
