# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 21:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0013_auto_20170415_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='changed_amount',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='changed_currency',
        ),
    ]
