# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0014_auto_20170415_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='changed_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='transactions',
            name='changed_currency',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
