# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0015_auto_20170415_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='user',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
