# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0016_transactions_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='changed_currency',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
