# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 22:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0018_auto_20170415_2224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactions',
            options={'get_latest_by': 'transfer_date'},
        ),
    ]
