# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 21:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0019_auto_20170415_2242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='local',
            new_name='cedis',
        ),
    ]
