# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0025_auto_20170420_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='contacts',
        ),
        migrations.AddField(
            model_name='settings',
            name='contacts',
            field=models.ManyToManyField(to='wallet.Contacts'),
        ),
    ]
