# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0026_auto_20170420_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='contacts',
        ),
    ]
