# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 17:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0028_auto_20170424_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='groups',
            field=models.ManyToManyField(null=True, to='wallet.Group'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
