# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0032_auto_20170427_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='userid',
        ),
    ]
