# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0034_auto_20170427_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='user',
        ),
        migrations.AddField(
            model_name='contacts',
            name='owner',
            field=models.CharField(default='', max_length=150),
        ),
    ]
