# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 19:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0035_auto_20170429_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='owner',
        ),
        migrations.AddField(
            model_name='contacts',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
