# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 20:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0037_auto_20170506_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
