# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0038_auto_20170506_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='groups',
        ),
        migrations.AddField(
            model_name='social',
            name='groups',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.Group'),
        ),
    ]
