# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0039_auto_20170506_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='groups',
        ),
        migrations.AddField(
            model_name='social',
            name='groups',
            field=models.ManyToManyField(to='wallet.Group'),
        ),
    ]
